### ISSUE TITLE
No emoji showed 

### ISSUE THREAD

**Issue by fabreg** [filipnet/ups-telegram-notify#2]
Hello,
the script works fine, I get the notification from Telegram but unfortunately no emoji are appearing.

![Screenshot from 2023-09-13 20-56-54](https://github.com/filipnet/ups-telegram-notify/assets/3074425/c41808c9-b4f2-49ed-984a-8d0cbeca132a)

If i pass

`-F "text=`echo -e '\U0001F514'`" \` (bell)

to the curl, I'm able to see the emoji  but there should be a better way.

Thank you!

**Comment by filipnet** [comment]
Hi, since we fortunately have few power outages in the region, I have not noticed this yet. But can reproduce the missing Emoji. In the script there was a wrong variable {$STATE} used, which is not passed. I changed this in the code to ${NOTIFYTYPE}, now it should work.

![image](https://github.com/filipnet/ups-telegram-notify/assets/63908077/ead77f5e-9e69-4123-8a09-4e5eb0a0803d)

**Comment by fabrizio-regalli** [comment]
Hi,
yes, right, with the new variables everything works as expected.

Thank you!

**Comment by fabreg** [comment]
Hi,

yes, right: with the new variable everything works as expected.

Thank you!
